//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fsci.client.Resources.TranslatedText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text_it {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text_it() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fsci.client.Resources.TranslatedText.Text.it", typeof(Text_it).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cambia la cartella di lavoro corrente.
        /// </summary>
        internal static string command_cd_description {
            get {
                return ResourceManager.GetString("command.cd.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nuova cartella di lavoro cambiata a: {0}.
        /// </summary>
        internal static string command_cd_success {
            get {
                return ResourceManager.GetString("command.cd.success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cd &lt;percorso&gt;.
        /// </summary>
        internal static string command_cd_synopsis {
            get {
                return ResourceManager.GetString("command.cd.synopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operazione fallita: non è stato possibile cambiare la cartella di lavoro corrente a {0}.
        /// </summary>
        internal static string command_cd_unsuccess {
            get {
                return ResourceManager.GetString("command.cd.unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pulisce l&apos;area di output.
        /// </summary>
        internal static string command_clear_description {
            get {
                return ResourceManager.GetString("command.clear.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        internal static string command_clear_synopsis {
            get {
                return ResourceManager.GetString("command.clear.synopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lista i comandi disponibili con la loro descrizione e sinossi.
        /// </summary>
        internal static string command_help_description {
            get {
                return ResourceManager.GetString("command.help.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string command_help_synopsis {
            get {
                return ResourceManager.GetString("command.help.synopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lista il contenuto della cartella di lavoro corrente.
        /// </summary>
        internal static string command_ls_description {
            get {
                return ResourceManager.GetString("command.ls.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ls.
        /// </summary>
        internal static string command_ls_synopsis {
            get {
                return ResourceManager.GetString("command.ls.synopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crea una nuova cartella nella cartella di lavoro corrente.
        /// </summary>
        internal static string command_mkdir_description {
            get {
                return ResourceManager.GetString("command.mkdir.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nuova cartella creata: {0}.
        /// </summary>
        internal static string command_mkdir_success {
            get {
                return ResourceManager.GetString("command.mkdir.success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mkdir &lt;nome cartella&gt;.
        /// </summary>
        internal static string command_mkdir_synopsis {
            get {
                return ResourceManager.GetString("command.mkdir.synopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operazione fallita: non è stato possibile create la cartella con nome {0}.
        /// </summary>
        internal static string command_mkdir_unsuccess {
            get {
                return ResourceManager.GetString("command.mkdir.unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sposta una cartella ed il suo contenuto in un&apos;altra cartella.
        /// </summary>
        internal static string command_mv_description {
            get {
                return ResourceManager.GetString("command.mv.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spostata la cartella {0} in {1}.
        /// </summary>
        internal static string command_mv_success {
            get {
                return ResourceManager.GetString("command.mv.success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mv &lt;origine&gt; &lt;destinazione&gt;.
        /// </summary>
        internal static string command_mv_synopsis {
            get {
                return ResourceManager.GetString("command.mv.synopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operazione fallita: non è stato possibile spostare la cartella {0} in {1}.
        /// </summary>
        internal static string command_mv_unsuccess {
            get {
                return ResourceManager.GetString("command.mv.unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: comando non trovato.
        /// </summary>
        internal static string command_notfound {
            get {
                return ResourceManager.GetString("command.notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stampa il percorso della cartella di lavoro corrente.
        /// </summary>
        internal static string command_pwd_description {
            get {
                return ResourceManager.GetString("command.pwd.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cartella di lavoro corrente: {0}.
        /// </summary>
        internal static string command_pwd_success {
            get {
                return ResourceManager.GetString("command.pwd.success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pwd.
        /// </summary>
        internal static string command_pwd_synopsis {
            get {
                return ResourceManager.GetString("command.pwd.synopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elimina una cartella ed il suo contenuto.
        /// </summary>
        internal static string command_rm_description {
            get {
                return ResourceManager.GetString("command.rm.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cartella {0} eliminata.
        /// </summary>
        internal static string command_rm_success {
            get {
                return ResourceManager.GetString("command.rm.success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rm &lt;percorso&gt;.
        /// </summary>
        internal static string command_rm_synopsis {
            get {
                return ResourceManager.GetString("command.rm.synopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operazione fallita: non è stato possibile eliminare la cartella al percorso {0}.
        /// </summary>
        internal static string command_rm_unsuccess {
            get {
                return ResourceManager.GetString("command.rm.unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: errore di sintassi (utilizzo {1}).
        /// </summary>
        internal static string command_syntaxerror {
            get {
                return ResourceManager.GetString("command.syntaxerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comando.
        /// </summary>
        internal static string ui_command {
            get {
                return ResourceManager.GetString("ui.command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci qui il comando.
        /// </summary>
        internal static string ui_enter_command {
            get {
                return ResourceManager.GetString("ui.enter_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua.
        /// </summary>
        internal static string ui_language {
            get {
                return ResourceManager.GetString("ui.language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interprete di Comandi di File System.
        /// </summary>
        internal static string ui_title {
            get {
                return ResourceManager.GetString("ui.title", resourceCulture);
            }
        }
    }
}
